version: '3'

volumes:
  # We'll define a volume that will store the data from the postgres databases:
  staffsso-data:
    driver: local

services:
  db:
    image: "postgres:10"
    restart: always
    environment:
      - POSTGRESS_PASSWORD=does-it-really-matter
    volumes:
     - staffsso-data:/var/lib/postgresql/data
    ports:
     - 2002:5432
  idp:
    build: ./extras/saml-idp-test/
    ports:
     - 8080:80
     - 8443:443
    environment:
     - SIMPLESAMLPHP_SP_ENTITY_ID=https://sso.staff.service.trade.gov.uk/sp
     - SIMPLESAMLPHP_SECRET_SALT=secret-salt

  web:
    env_file:
      - .env
    environment:
      - PORT=8000
    build: .
    ports:
     - 2000:8000
    depends_on:
     - db
     - idp
    command: python3 manage.py runserver 0.0.0.0:8000


